# Generated by Django 6.0.4 on 2026-04-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('complexity', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueness_score', models.FloatField(default=0)),
                ('feasibility_score', models.FloatField(default=0)),
                ('impact_score', models.FloatField(default=0)),
                ('innovation_score', models.FloatField(default=0)),
                ('competition_level', models.CharField(default='Low', max_length=20)),
                ('competition_detail', models.TextField(blank=True, default='')),
                ('similarity', models.FloatField(default=0)),
                ('keywords', models.JSONField(default=list)),
                ('weighted_keywords', models.JSONField(default=list)),
                ('github_repos', models.JSONField(default=list)),
                ('github_total_count', models.IntegerField(default=0)),
                ('github_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='IdeaApp.idea')),
            ],
        ),
    ]
