# Generated by Django 5.2.8 on 2026-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='score_reasons',
            field=models.JSONField(default=dict),
        ),
    ]
